name: Dev Branch CI

# Only run on dev branch
on:
  push:
    branches:
      - dev

jobs:
  # Stage 1: Unit Tests
  unit-test-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies if requirements.txt exists
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run Python unit tests
      - name: Run Unit Tests
        run: python3 -m unittest discover -s tests -p "*.py"

  # Stage 2: Merge Request (Pull Request)
  create-merge-request:
    runs-on: ubuntu-latest
    needs: unit-test-job               # Only run if tests pass
    if: github.ref == 'refs/heads/dev' # Only run on dev branch
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Create Pull Request via GitHub API using curl
      - name: Create Pull Request via curl
        env:
          GH_TOKEN: ${{ secrets.API_TOKEN }}  # GitHub secret
          REPO: ${{ github.repository }}      # owner/repo
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$REPO/pulls \
            -d '{"title":"Auto merge dev to main","head":"dev","base":"main","body":"Created automatically by workflow"}'
